
export const teams = [
    {"id":"FA",  "location":"Free",          "name":"Agent"},
    {"id":"ARI", "location":"Arizona",       "name":"Cardinals"},
    {"id":"ATL", "location":"Atlanta",       "name":"Falcons"},
    {"id":"BAL", "location":"Baltimore",     "name":"Ravens"},
    {"id":"BUF", "location":"Buffalo",       "name":"Bills"},
    {"id":"CAR", "location":"Carolina",      "name":"Panthers"},
    {"id":"CHI", "location":"Chicago",       "name":"Bears"},
    {"id":"CIN", "location":"Cincinnati",    "name":"Bengals"},
    {"id":"CLE", "location":"Cleveland",     "name":"Browns"},
    {"id":"DAL", "location":"Dallas",        "name":"Cowboys"},
    {"id":"DEN", "location":"Denver",        "name":"Broncos"},
    {"id":"DET", "location":"Detroit",       "name":"Lions"},
    {"id":"GB",  "location":"Green Bay",     "name":"Packers"},
    {"id":"HOU", "location":"Houston",       "name":"Texans"},
    {"id":"IND", "location":"Indianapolis",  "name":"Colts"},
    {"id":"JAX", "location":"Jacksonville",  "name":"Jaguars"},
    {"id":"KC",  "location":"Kansas City",   "name":"Chiefs"},
    {"id":"LV",  "location":"Las Vegas",     "name":"Raiders"},
    {"id":"LAR", "location":"Los Angeles",   "name":"Rams"},
    {"id":"MIA", "location":"Miami",         "name":"Dolphins"},
    {"id":"MIN", "location":"Minnesota",     "name":"Vikings"},
    {"id":"NE",  "location":"New England",   "name":"Patriots"},
    {"id":"NO",  "location":"New Orleans",   "name":"Saints"},
    {"id":"NYG", "location":"New York",      "name":"Giants"},
    {"id":"NYJ", "location":"New York",      "name":"Jets"},
    {"id":"PHI", "location":"Philadelphia",  "name":"Eagles"},
    {"id":"PIT", "location":"Pittsburgh",    "name":"Steelers"},
    {"id":"SEA", "location":"Seattle",       "name":"Seahawks"},
    {"id":"SF",  "location":"San Francisco", "name":"49ers"},
    {"id":"TB",  "location":"Tampa Bay",     "name":"Buccaneers"},
    {"id":"TEN", "location":"Tennessee",     "name":"Titans"},
    {"id":"LAC", "location":"Los Angeles",   "name":"Chargers"},
    {"id":"WSH", "location":"Washington",    "name":"Commanders"}
];
