export const positions = [
  { id: 'QB', name: 'Quarterback' },
  { id: 'RB', name: 'Running Back' },
  { id: 'WR', name: 'Wide Receiver' },
  { id: 'TE', name: 'Tight End' },
  { id: 'DST', name: 'Defensive Team' },
  { id: 'K', name: 'Kicker' },
  { id: 'OT', name: 'Offensive Tackle' },
  { id: 'G', name: 'Guard' },
  { id: 'C', name: 'Center' },
  { id: 'DE', name: 'Defensive End' },
  { id: 'DT', name: 'Defensive Tackle' },
  { id: 'LB', name: 'Linebacker' },
  { id: 'CB', name: 'Cornerback' },
  { id: 'S', name: 'Safety' },
  { id: 'FB', name: 'Fullback' },
  { id: 'LS', name: 'Long Snapper' },
  { id: 'P', name: 'Punter' },
];
